networks:
  shared-network:
    external: true

volumes:
  app_storage:
  laravel_cache:

services:
  app-absensi:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-absensi
      args:
        - GIT_HASH=${GIT_HASH:-unknown}
    container_name: absensi_track_app
    restart: unless-stopped
    working_dir: /var/www/absensi_track
    env_file: .env
    volumes:
      - app_storage:/var/www/absensi_track/storage
      - laravel_cache:/var/www/absensi_track/bootstrap/cache
    networks:
      - shared-network

  nginx:
    image: nginx:alpine
    container_name: absensi_track_nginx
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=absensi-track.bornhub.cloud
      - LETSENCRYPT_HOST=absensi-track.bornhub.cloud
      - LETSENCRYPT_EMAIL=ahmadfauzanroziqin@gmail.com
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/absensi_track
    networks:
      - shared-network 
    depends_on:
      - app-absensi  
      - worker

  worker: 
    build:
      context: .
      dockerfile: Dockerfile
      target: app-absensi
      args:
        - GIT_HASH=${GIT_HASH:-unknown}
    container_name: absensi_track_queue
    restart: unless-stopped
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    env_file: .env
    working_dir: /var/www/absensi_track
    volumes:
      - app_storage:/var/www/absensi_track/storage
      - laravel_cache:/var/www/absensi_track/bootstrap/cache
    networks:
      - shared-network 
    depends_on:
      - app-absensi