[supervisord]
nodaemon=true

[program:queue]
command=php artisan queue:work --sleep=1 --tries=3 --max-time=3600
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/absensi_track/storage/logs/queue.log
user=www-data
startsecs=2
stopwaitsecs=10

[program:reverb]
; pastikan binding ke semua interface di container
command=php artisan reverb:start --host=0.0.0.0 --port=8080
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/absensi_track/storage/logs/reverb.log
user=www-data
startsecs=2
stopwaitsecs=10
