[supervisord]
nodaemon=true
user=www

[program:queue]
command=php /var/www/absensi_track/artisan queue:work --sleep=1 --tries=3 --max-time=3600
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/html/absensi_track/logs/queue.log

# [program:schedule]
# ; jalankan scheduler tiap 60 detik
# command=php /var/www/html/artisan schedule:work
# autostart=true
# autorestart=true
# redirect_stderr=true
# stdout_logfile=/var/www/html/storage/logs/schedule.log
